# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8428654c617cba5c6b997dbebc0a2565fada43e59ff083c108fe85ddbaa57c1adec3d2ae2f6ab644684d9a61e700b0b4bb855f0014524bdda36c53ea80e134e0

test:
  secret_key_base: 76d373eda177a03c555f0ed6d6d5d7e75e1754f1b38c2d46e9a65b553940640b21a3d75476dec6097c1e4dc787b226025d52e1501d9a02381908e24d0bbae697

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
